name: News Auto Update

on:
  schedule:
    # every 3 hours, at minute 0
    - cron: "0 */3 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate feeds (top & trending)
        run: |
          python pull_news.py

      - name: Commit & push generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/top.json data/trending.json || true
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update news (3h)"
            git push
          else
            echo "No changes to commit"
          fi
