#!/usr/bin/env node
import path from "path";
import {pathToFileURL} from "url";
const arg=(n,d)=>{const i=process.argv.indexOf(n);return i>=0&&process.argv[i+1]?process.argv[i+1]:d};
const ok=(v,m)=>{if(!v)throw new Error(m)};
const engine=path.resolve(arg("--engine","scripts/cosmos_universal_object_model_v0.1.mjs"));
const {buildUniversalObjectModel}=await import(pathToFileURL(engine).href);
const fixture={schema_version:"fixture-0.1",objects:[
{id:"video-1",label:"Humanoid Robots Explained",kind:"content",domains:["media","robotics"],representations:[{id:"rep-youtube",media_type:"video/youtube",role:"primary",locator:{scheme:"youtube",value:"fixture-video-id"}}],epistemic_status:"observed"},
{id:"person-1",label:"Researcher",kind:"person",domains:["ai","robotics"]},{id:"model-1",label:"AI Model",kind:"model",domains:["ai"]},{id:"company-1",label:"Robotics Company",kind:"organization",domains:["robotics","markets"]},{id:"concept-1",label:"Humanoid Robotics",kind:"concept"},{id:"question-1",label:"What changes next?",kind:"question"},{id:"relationship-focus",label:"AI Model accelerates Humanoid Robotics",kind:"relationship"}],relationships:[
{id:"r1",from:"video-1",to:"concept-1",predicate:"discusses",confidence:92,epistemic_status:"supported"},{id:"r2",from:"person-1",to:"video-1",predicate:"appears_in",confidence:88,epistemic_status:"supported"},{id:"r3",from:"model-1",to:"concept-1",predicate:"enables",confidence:76,epistemic_status:"scenario"},{id:"r4",from:"company-1",to:"concept-1",predicate:"develops",confidence:82,epistemic_status:"supported"},{id:"r5",from:"question-1",to:"concept-1",predicate:"asks_about"},{id:"r6",from:"relationship-focus",to:"model-1",predicate:"references"}]};
const r=buildUniversalObjectModel(fixture);ok(r.status==="universal_cosmos_object_model_resolved","status");ok(r.integrity.valid,"integrity");ok(r.objects.length===7&&r.relationships.length===6,"counts");ok(r.objects.every(o=>o.observer_capabilities.can_be_center),"center");ok(r.objects.find(o=>o.id==="video-1").representations.some(x=>x.locator?.scheme==="youtube"),"youtube");ok(r.objects.find(o=>o.id==="model-1")?.kind==="model","model");ok(r.objects.find(o=>o.id==="question-1")?.kind==="question","question");ok(r.objects.find(o=>o.id==="relationship-focus")?.kind==="relationship","relationship focus");const c=r.contracts;ok(c.any_object_can_be_observer_center&&c.permanent_domain_silos_required===false&&c.media_is_representation_or_object_not_navigation_silo&&c.youtube_can_be_content_source_representation_or_evidence&&c.relationship_can_be_observer_focus,"contracts");const s=r.safeguards;ok(s.calls_openai_or_external_api===false&&s.forces_power_industry_ontology===false&&s.forces_media_silo===false&&s.forces_fixed_hierarchy===false,"safeguards");console.log(JSON.stringify({schema_version:"0.1",status:"universal_cosmos_object_model_test_passed",object_count:r.integrity.object_count,relationship_count:r.integrity.relationship_count,object_kinds:r.objects.map(o=>({id:o.id,kind:o.kind})),contracts:r.contracts,safeguards:r.safeguards},null,2));
