#!/usr/bin/env node
import fs from "fs";
import path from "path";
const arg=(n,d="")=>{const i=process.argv.indexOf(n);return i>=0&&process.argv[i+1]?process.argv[i+1]:d};
const clean=(v,d="")=>{const s=(v??"").toString().trim();return s||d};
const arr=v=>Array.isArray(v)?v:[];
const uniq=v=>[...new Set(arr(v).filter(Boolean))];
const OBJECT_KINDS=new Set(["thing","person","organization","place","event","concept","technology","asset","content","media","document","dataset","software","model","market","instrument","project","material","infrastructure","process","signal","claim","question","relationship","observation","source","unknown"]);
function locator(v){if(!v||typeof v!=="object")return null;return{scheme:clean(v.scheme,"unknown"),value:clean(v.value),label:clean(v.label)||null}}
function representation(v){if(!v||typeof v!=="object")return null;return{id:clean(v.id),media_type:clean(v.media_type,"application/octet-stream"),role:clean(v.role,"representation"),locator:locator(v.locator),metadata:v.metadata&&typeof v.metadata==="object"?v.metadata:{}}}
function evref(v){if(typeof v==="string")return{id:v,role:"support"};if(!v||typeof v!=="object")return null;return{id:clean(v.id),role:clean(v.role,"support"),source_object_id:clean(v.source_object_id)||null,representation_id:clean(v.representation_id)||null}}
export function normalizeCosmosObject(input){
 if(!input||typeof input!=="object")throw new Error("Object input required");
 const id=clean(input.id); if(!id)throw new Error("Cosmos object id is required");
 const raw=clean(input.kind||input.type,"unknown").toLowerCase(); const kind=OBJECT_KINDS.has(raw)?raw:"unknown";
 return{schema_version:"0.1",id,label:clean(input.label||input.title||input.name,id),kind,kind_raw:raw,description:clean(input.description)||null,
 identity:{aliases:uniq(input.aliases),external_ids:arr(input.external_ids).filter(x=>x&&typeof x==="object"),canonical_locator:locator(input.canonical_locator)},
 dimensions:{temporal:{state:clean(input.temporal_state||input?.dimensions?.temporal?.state,"unknown"),valid_from:input.valid_from??input?.dimensions?.temporal?.valid_from??null,valid_to:input.valid_to??input?.dimensions?.temporal?.valid_to??null,observed_at:input.observed_at??input?.dimensions?.temporal?.observed_at??null},geography:{scope:input.geography_scope??input?.dimensions?.geography?.scope??null,places:uniq(input.places||input?.dimensions?.geography?.places)},domains:uniq(input.domains||input?.dimensions?.domains),facets:input.facets&&typeof input.facets==="object"?input.facets:input?.dimensions?.facets&&typeof input.dimensions.facets==="object"?input.dimensions.facets:{}},
 epistemic:{status:clean(input.epistemic_status||input?.epistemic?.status,"unqualified"),confidence:Number.isFinite(Number(input.confidence??input?.epistemic?.confidence))?Number(input.confidence??input.epistemic.confidence):null,qualification:input.qualification??input?.epistemic?.qualification??null,provenance:arr(input.provenance||input?.epistemic?.provenance)},
 representations:arr(input.representations).map(representation).filter(Boolean),evidence_refs:arr(input.evidence_refs).map(evref).filter(Boolean),relationships:{incoming:uniq(input?.relationships?.incoming),outgoing:uniq(input?.relationships?.outgoing)},observer_capabilities:{can_be_center:true,can_be_represented_by_multiple_media:true,can_have_multiple_roles:true,can_participate_in_relationships:true,can_accumulate_evidence:true,can_change_over_time:true},metadata:input.metadata&&typeof input.metadata==="object"?input.metadata:{}}}
export function normalizeCosmosRelationship(input){if(!input||typeof input!=="object")throw new Error("Relationship input required");const id=clean(input.id),from=clean(input.from),to=clean(input.to);if(!id||!from||!to)throw new Error("Relationship id/from/to required");return{schema_version:"0.1",id,from,to,predicate:clean(input.predicate||input.relationship,"related_to"),direction:clean(input.direction,"directed"),relationship_kind:clean(input.relationship_kind,"semantic"),temporal_state:clean(input.temporal_state,"unknown"),geography_scope:input.geography_scope??null,epistemic_status:clean(input.epistemic_status,"unqualified"),confidence:Number.isFinite(Number(input.confidence))?Number(input.confidence):null,qualification:input.qualification??null,evidence_refs:arr(input.evidence_refs).map(evref).filter(Boolean),metadata:input.metadata&&typeof input.metadata==="object"?input.metadata:{}}}
export function buildUniversalObjectModel(dataset){const objects=arr(dataset?.objects).map(normalizeCosmosObject);const relationships=arr(dataset?.relationships).map(normalizeCosmosRelationship);const ids=new Set(objects.map(o=>o.id));const broken=relationships.filter(r=>!ids.has(r.from)||!ids.has(r.to)).map(r=>r.id);const dup=objects.map(o=>o.id).filter((id,i,a)=>a.indexOf(id)!==i);return{schema_version:"0.1",status:"universal_cosmos_object_model_resolved",objects,relationships,integrity:{object_count:objects.length,relationship_count:relationships.length,duplicate_object_ids:uniq(dup),broken_relationship_ids:broken,valid:dup.length===0&&broken.length===0},contracts:{any_object_can_be_observer_center:true,permanent_domain_silos_required:false,object_kind_is_extensible:true,media_is_representation_or_object_not_navigation_silo:true,youtube_can_be_content_source_representation_or_evidence:true,ai_model_can_be_object:true,person_can_be_object:true,company_can_be_object:true,market_can_be_object:true,question_can_be_object:true,relationship_can_be_observer_focus:true,multiple_representations_supported:true,multiple_roles_supported:true,temporal_dimension_supported:true,geography_dimension_supported:true,epistemic_state_supported:true,evidence_lineage_supported:true},safeguards:{performs_external_search:false,calls_openai_or_external_api:false,mutates_source_graph:false,invents_missing_evidence:false,forces_power_industry_ontology:false,forces_media_silo:false,forces_fixed_hierarchy:false,collapses_object_to_single_role:false}}}
async function main(){const input=arg("--input"),out=arg("--out");if(!input)throw new Error("--input is required");const dataset=JSON.parse(fs.readFileSync(input,"utf8"));const result=buildUniversalObjectModel(dataset);if(out){fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(result,null,2))}console.log(JSON.stringify(result,null,2))}
if(process.argv[1]&&path.resolve(process.argv[1])===path.resolve(new URL(import.meta.url).pathname)){main().catch(e=>{console.error(e);process.exit(1)})}
