#!/usr/bin/env node
import path from "node:path";import process from "node:process";import{pathToFileURL}from"node:url";
const arg=(n,d="")=>{const i=process.argv.indexOf(n);return i>=0&&process.argv[i+1]?process.argv[i+1]:d};const assert=(v,m)=>{if(!v)throw new Error(m)};
const{buildCenterIntelligence}=await import(pathToFileURL(path.resolve(arg("--engine"))).href);
const entities=[{entity_id:"gis",name:"Gas-Insulated Switchgear",description:"Compact high-voltage switchgear using gas insulation."},{entity_id:"sf6",name:"SF6"},{entity_id:"substations",name:"Substations"}];
const developments=[{development_id:"old1",article_id:"article-old-gis",title:"GIS modernization remains active",summary:"Utilities continue replacing aging high-voltage equipment.",why_it_matters:"Replacement cycles affect utility capital planning.",entity_ids:["gis","substations"]},{development_id:"old2",article_id:"article-sf6",title:"SF6 alternatives gain attention",summary:"Manufacturers continue evaluating lower-GWP insulation technologies.",entity_ids:["gis","sf6"]}];
const dailyBrief=[{development_id:"today1",article_id:"article-today-gis",title:"GIS procurement pressure appears in current projects",summary:"Current projects show procurement attention around GIS equipment.",entity_ids:["gis","substations"]}];
const r=buildCenterIntelligence({entity:entities[0],developments,dailyBrief,entities});
assert(r.status==="cosmos_center_intelligence_resolved","status");assert(r.what_is_this.includes("Compact high-voltage"),"description");assert(r.record_counts.related===3,"records");assert(r.record_counts.current===1,"today");assert(r.article_cards.length===3,"articles");assert(r.article_cards.every(x=>x.follow_ripple_expected),"ripple");assert(r.curiosity_paths.some(x=>x.id==="substations"),"curiosity");assert(r.why_it_matters.includes("capital planning"),"why");assert(Object.values(r.contracts).every(Boolean),"contracts");assert(Object.values(r.safeguards).every(v=>v===false),"safeguards");
console.log(JSON.stringify({schema_version:"0.1",status:"cosmos_center_intelligence_test_passed",record_counts:r.record_counts,article_count:r.article_cards.length,curiosity_count:r.curiosity_paths.length,contracts:r.contracts,safeguards:r.safeguards},null,2));
