#!/usr/bin/env node
import fs from "node:fs";import os from "node:os";import path from "node:path";import {pathToFileURL} from "node:url";
const arg=(n,d="")=>{const i=process.argv.indexOf(n);return i>=0&&process.argv[i+1]?process.argv[i+1]:d};const assert=(v,m)=>{if(!v)throw new Error(m)};
const mod=await import(pathToFileURL(path.resolve(arg("--engine"))).href);
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),"cosmos-kc-candidate-pipeline-"));const sd=path.join(tmp,"scripts"),od=path.join(tmp,"out");fs.mkdirSync(sd,{recursive:true});
const acquisition={schema_version:"0.1",status:"acquisition_plans_resolved",source_discovery:{schema_version:"0.1"},acquisition_state:{plan_count:1,execution_mode:"planned_only",external_execution_connected:false,evidence_validation_required_before_graph_admission:true,conceptual_distance_limit:null,continuation_possible:true},acquisition_plans:[{acquisition_plan_id:"plan_1",discovery_target_id:"target_1",target_type:"identify_components",statement:"Identify supported components of HV Substations.",execution:{mode:"planned_only",network_execution_performed:false,executor_status:"not_connected",result_count:0},evidence_contract:{evidence_is_not_knowledge_until_validated:true,knowledge_admission_status:"not_evaluated"}}],future_executor_queue:[{acquisition_plan_id:"plan_1",execution_status:"not_connected"}]};
const af=path.join(tmp,"acquisition.json");fs.writeFileSync(af,JSON.stringify(acquisition,null,2));
const stage=body=>`#!/usr/bin/env node
const fs=require("fs"),path=require("path");const a=n=>{const i=process.argv.indexOf(n);return i>=0?process.argv[i+1]:null};const input=a("--input"),out=a("--out");const src=JSON.parse(fs.readFileSync(input,"utf8"));const payload=${body};fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(payload,null,2));`;
fs.writeFileSync(path.join(sd,"app.cjs"),stage(`({schema_version:"0.1",status:"acquisition_applicability_resolved",source_acquisition:{schema_version:src.schema_version},applicability_state:{external_execution_connected:false,conceptual_distance_limit:null,continuation_possible:true},evaluations:[{acquisition_plan_id:"plan_1",discovery_target_id:"target_1",target_type:"identify_components",original_statement:"x",subject:"HV Substations",applicability_status:"decomposition_required",executable:false}],executable_queue:[],decomposition_queue:[{acquisition_plan_id:"plan_1"}]})`));
fs.writeFileSync(path.join(sd,"decomp.cjs"),stage(`({schema_version:"0.1",status:"decomposition_candidates_resolved",source_applicability:{schema_version:src.schema_version},decomposition_state:{blocked_plan_count:1,candidate_count:2,validated_candidate_count:0,executable_candidate_count:0,external_execution_connected:false,conceptual_distance_limit:null,continuation_possible:true},decompositions:[{decomposition_id:"dec_1",acquisition_plan_id:"plan_1",discovery_target_id:"target_1",abstract_subject:"HV Substations",original_target_type:"identify_components",status:"provisional_candidates_resolved",candidates:[{decomposition_candidate_id:"candidate_a",epistemic_status:"provisional_candidate",validated:false,executable:false},{decomposition_candidate_id:"candidate_b",epistemic_status:"provisional_candidate",validated:false,executable:false}]}],candidate_validation_queue:[{decomposition_candidate_id:"candidate_a"},{decomposition_candidate_id:"candidate_b"}]})`));
fs.writeFileSync(path.join(sd,"candidate.cjs"),stage(`({schema_version:"0.1",status:"candidate_validation_targets_resolved",source_decomposition:{schema_version:src.schema_version},validation_state:{raw_candidate_count:2,unique_validation_target_count:2,duplicate_candidate_count:0,validated_target_count:0,executable_target_count:0,external_execution_connected:false,conceptual_distance_limit:null,continuation_possible:true},validation_targets:[{validation_target_id:"validation_a",epistemic_status:"provisional_candidate",validation_status:"not_started",executable:false,knowledge_status:"not_admitted"},{validation_target_id:"validation_b",epistemic_status:"provisional_candidate",validation_status:"not_started",executable:false,knowledge_status:"not_admitted"}],future_evidence_queue:[{validation_target_id:"validation_a"},{validation_target_id:"validation_b"}]})`));
const result=mod.runCandidatePipeline({acquisition:af,out_dir:od,scripts:{applicability:path.join(sd,"app.cjs"),decomposition:path.join(sd,"decomp.cjs"),candidate_validation:path.join(sd,"candidate.cjs")}});
assert(result.status==="knowledge_completion_candidate_pipeline_resolved","pipeline");assert(result.stage_order.join(">")==="acquisition_applicability>decomposition>candidate_validation","order");assert(result.counts.provisional_candidates===2,"candidates");assert(result.counts.validation_targets===2,"targets");assert(result.next_stage==="evidence_strategy","next");assert(Object.values(result.boundaries).every(v=>v===false),"boundaries");assert(Object.values(result.contracts).every(v=>v===true),"contracts");assert(Object.values(result.safeguards).every(v=>v===false),"safeguards");
let blocked=false;const bad=JSON.parse(fs.readFileSync(path.join(od,"decomposition.json"),"utf8"));bad.decompositions[0].candidates[0].validated=true;try{mod.validateDecomposition(bad)}catch(e){blocked=true}assert(blocked,"promotion blocked");
console.log(JSON.stringify({schema_version:"0.1",status:"cosmos_knowledge_completion_candidate_pipeline_test_passed",stage_order:result.stage_order,counts:result.counts,next_stage:result.next_stage,premature_candidate_promotion_blocked:blocked,contracts:result.contracts,boundaries:result.boundaries,safeguards:result.safeguards},null,2));
