// scripts/generate_sitemap_articles.js
// PTD Today / Cosmos — curated article sitemap + root sitemap index
//
// Goals:
// 1) Keep legacy/generated article files accessible but stop advertising them.
// 2) Keep sitemap.xml stable after every Home AI run.
// 3) Always advertise the active Cosmos sitemap.
//
// Excluded from sitemap-articles.xml:
//   articles/dev_*.html
//   articles/dev-*.html
//   articles/ai-*.html
//
// The files themselves are NOT deleted or redirected.

import fs from "fs";
import path from "path";

const SITE_ORIGIN = String(
  process.env.SITE_ORIGIN || "https://ptdtoday.com"
).replace(/\/+$/, "");

const ARTICLES_DIR = process.env.ARTICLES_DIR || "articles";
const ARTICLES_SITEMAP_FILE =
  process.env.SITEMAP_ARTICLES_FILE || "sitemap-articles.xml";
const ROOT_SITEMAP_FILE =
  process.env.SITEMAP_INDEX_FILE || "sitemap.xml";

function xmlEscape(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function isGeneratedLegacyArticle(fileName) {
  const name = String(fileName || "").toLowerCase();
  if (/^dev[_-].*\.html$/.test(name)) return true;
  if (/^ai-.*\.html$/.test(name)) return true;
  return false;
}

function articleFiles() {
  if (!fs.existsSync(ARTICLES_DIR)) return [];

  return fs
    .readdirSync(ARTICLES_DIR)
    .filter((name) => name.toLowerCase().endsWith(".html"))
    .filter((name) => !isGeneratedLegacyArticle(name))
    .sort((a, b) => a.localeCompare(b));
}

function articleSitemapRow(fileName) {
  const fullPath = path.join(ARTICLES_DIR, fileName);
  const stat = fs.statSync(fullPath);
  const url = `${SITE_ORIGIN}/articles/${encodeURIComponent(fileName)}`;

  return [
    "  <url>",
    `    <loc>${xmlEscape(url)}</loc>`,
    `    <lastmod>${xmlEscape(stat.mtime.toISOString())}</lastmod>`,
    "  </url>"
  ].join("\n");
}

function writeArticleSitemap(files) {
  const rows = files.map(articleSitemapRow);

  const xml =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    `${rows.join("\n")}${rows.length ? "\n" : ""}` +
    `</urlset>\n`;

  fs.writeFileSync(ARTICLES_SITEMAP_FILE, xml, "utf8");
}

function rootSitemapEntry(url, lastmod = "") {
  return [
    "  <sitemap>",
    `    <loc>${xmlEscape(url)}</loc>`,
    lastmod ? `    <lastmod>${xmlEscape(lastmod)}</lastmod>` : "",
    "  </sitemap>"
  ].filter(Boolean).join("\n");
}

function writeRootSitemapIndex(curatedArticleCount) {
  const now = new Date().toISOString();

  const entries = [
    rootSitemapEntry(`${SITE_ORIGIN}/sitemap-main.xml`, now),
    rootSitemapEntry(`${SITE_ORIGIN}/sitemap-cosmos.xml`, now)
  ];

  if (curatedArticleCount > 0) {
    entries.push(
      rootSitemapEntry(`${SITE_ORIGIN}/sitemap-articles.xml`, now)
    );
  }

  const xml =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    `${entries.join("\n")}\n` +
    `</sitemapindex>\n`;

  fs.writeFileSync(ROOT_SITEMAP_FILE, xml, "utf8");
}

function main() {
  const allHtml = fs.existsSync(ARTICLES_DIR)
    ? fs
        .readdirSync(ARTICLES_DIR)
        .filter((name) => name.toLowerCase().endsWith(".html"))
    : [];

  const files = articleFiles();
  const excluded = allHtml.length - files.length;

  writeArticleSitemap(files);
  writeRootSitemapIndex(files.length);

  console.log(
    `Article sitemap updated: ${files.length} curated article(s) included, ` +
    `${excluded} autogenerated/legacy article(s) excluded.`
  );

  console.log(
    `Root sitemap updated with sitemap-main.xml + sitemap-cosmos.xml` +
    `${files.length > 0 ? " + sitemap-articles.xml" : ""}.`
  );
}

main();
