// scripts/generate_sitemap_articles.js
// PTD Today / Cosmos — curated article sitemap generator
//
// Keeps article files accessible, but excludes autogenerated legacy/scenario
// article URLs from sitemap advertising.
//
// Excluded:
//   articles/dev_*.html
//   articles/dev-*.html
//   articles/ai-*.html

import fs from "fs";
import path from "path";

const SITE_ORIGIN = String(
  process.env.SITE_ORIGIN || "https://ptdtoday.com"
).replace(/\/+$/, "");

const ARTICLES_DIR = process.env.ARTICLES_DIR || "articles";
const OUTPUT_FILE =
  process.env.SITEMAP_ARTICLES_FILE || "sitemap-articles.xml";

function xmlEscape(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function isGeneratedLegacyArticle(fileName) {
  const name = String(fileName || "").toLowerCase();
  if (/^dev[_-].*\.html$/.test(name)) return true;
  if (/^ai-.*\.html$/.test(name)) return true;
  return false;
}

function articleFiles() {
  if (!fs.existsSync(ARTICLES_DIR)) return [];

  return fs
    .readdirSync(ARTICLES_DIR)
    .filter((name) => name.toLowerCase().endsWith(".html"))
    .filter((name) => !isGeneratedLegacyArticle(name))
    .sort((a, b) => a.localeCompare(b));
}

function sitemapRow(fileName) {
  const fullPath = path.join(ARTICLES_DIR, fileName);
  const stat = fs.statSync(fullPath);
  const url = `${SITE_ORIGIN}/articles/${encodeURIComponent(fileName)}`;

  return [
    "  <url>",
    `    <loc>${xmlEscape(url)}</loc>`,
    `    <lastmod>${xmlEscape(stat.mtime.toISOString())}</lastmod>`,
    "  </url>"
  ].join("\n");
}

function main() {
  const allHtml = fs.existsSync(ARTICLES_DIR)
    ? fs.readdirSync(ARTICLES_DIR)
        .filter((name) => name.toLowerCase().endsWith(".html"))
    : [];

  const files = articleFiles();
  const excluded = allHtml.length - files.length;
  const rows = files.map(sitemapRow);

  const xml =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    `${rows.join("\n")}${rows.length ? "\n" : ""}` +
    `</urlset>\n`;

  fs.writeFileSync(OUTPUT_FILE, xml, "utf8");

  console.log(
    `Article sitemap updated: ${files.length} curated article(s) included, ` +
    `${excluded} autogenerated/legacy article(s) excluded.`
  );
}

main();
