name: Daily Energy Headlines

on:
  # Runs every day at 10:30 UTC (≈ 6:30 AM Eastern during DST)
  schedule:
    - cron: "30 10 * * *"
  # Keep the manual button in Actions → “Run workflow”
  workflow_dispatch: {}

# Let this workflow push the generated files back to your repo
permissions:
  contents: write

# Avoid overlapping runs
concurrency:
  group: daily-energy-headlines
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install feedparser python-dateutil beautifulsoup4 html5lib

      - name: Generate news JSON + LinkedIn text
        run: python pull_news.py

      - name: Commit & push generated files
        run: |
          git config user.name "news-bot"
          git config user.email "actions@users.noreply.github.com"
          git add data/top.json data/linkedin.txt
          git commit -m "daily: update headlines" || echo "No changes to commit"
          git push
