name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"   # every 3 hours

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # ---- INSTALL DEPS (robust) ----
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If your requirements.txt is in the repo root, keep this:
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # If it's in daily-news/, also install from there (safe even if not present):
          if [ -f daily-news/requirements.txt ]; then pip install -r daily-news/requirements.txt; fi
          # Ensure critical packages are present even without requirements.txt
          pip install --upgrade requests feedparser beautifulsoup4 lxml python-dateutil

      - name: Show Python and installed packages (debug)
        run: |
          which python
          python --version
          python -c "import sys, pkgutil; print('requests' in [m.name for m in pkgutil.iter_modules()])"
          pip list | sed -n '1,120p'

      # ---- RUN YOUR SCRIPT ----
      # If pull_news.py is under daily-news/, run with that working directory
      - name: Generate news JSON + LinkedIn text
        working-directory: daily-news
        run: python pull_news.py

      - name: Commit & push generated files
        run: |
          git config user.name "ptdtoday-bot"
          git config user.email "bot@ptdtoday.com"
          git add -A
          git commit -m "chore: refresh news" || echo "no changes"
          git push
