name: Daily Energy Headlines

on:
  schedule:
    - cron: "30 10 * * *"   # ~6:30 AM Eastern during DST
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: daily-energy-headlines
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install feedparser python-dateutil beautifulsoup4 html5lib

      - name: Generate news JSON + LinkedIn text
        run: python pull_news.py

      - name: Commit & push generated files
        run: |
          git config user.name "news-bot"
          git config user.email "actions@users.noreply.github.com"
          git add data/top.json data/linkedin.txt
          git commit -m "daily: update headlines" || echo "No changes to commit"
          git push
          
