name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "7 */3 * * *"   # every 3 hours
  push:
    paths:
      - "pull_news.py"
      - "requirements.txt"
      - ".github/workflows/ptd-build.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate news + shortlinks
        run: |
          python pull_news.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: refresh news ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
            git push
          else
            echo "No changes – nothing to commit."
          fi
