name: Build PTD Today (3h)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"   # every 3 hours UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate news + shortlinks
        run: |
          python3 pull_news.py

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: refresh news (${{ github.run_id }})" || echo "Nothing to commit"
          git push