name: PTD Today – build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"   # every 3 hours

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate shortlinks + JSON
        run: python pull_news.py

      - name: Commit & push generated files
        run: |
          git config user.name "ptdtoday-bot"
          git config user.email "bot@ptdtoday.com"
          git add -A
          git commit -m "chore: build shortlinks + data" || echo "no changes"
          git push
