name: Build PTD Today (3h)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"  # every 3 hours UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate news + shortlinks
        run: python pull_news.py

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/news.json data/shortlinks.json s/ || true
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore: refresh news ($(date -u +%Y-%m-%dT%H:%M:%SZ))"
            git push
          fi